export default [
  {
    paletteName: "Material UI Colors",
    id: "material-ui-colors",
    emoji: "🎨",
    colors: [
      { name: "red", color: "#F44336" },
      { name: "pink", color: "#E91E63" },
      { name: "purple", color: "#9C27B0" },
      { name: "deeppurple", color: "#673AB7" },
      { name: "indigo", color: "#3F51B5" },
      { name: "blue", color: "#2196F3" },
      { name: "lightblue", color: "#03A9F4" },
      { name: "cyan", color: "#00BCD4" },
      { name: "teal", color: "#009688" },
      { name: "green", color: "#4CAF50" },
      { name: "lightgreen", color: "#8BC34A" },
      { name: "lime", color: "#CDDC39" },
      { name: "yellow", color: "#FFEB3B" },
      { name: "amber", color: "#FFC107" },
      { name: "orange", color: "#FF9800" },
      { name: "deeporange", color: "#FF5722" },
      { name: "brown", color: "#795548" },
      { name: "grey", color: "#9E9E9E" },
      { name: "bluegrey", color: "#607D8B" },
    ],
  },
  {
    paletteName: "Flat UI Colors v1",
    id: "flat-ui-colors-v1",
    emoji: "🤙",
    colors: [
      { name: "Turquoise", color: "#1abc9c" },
      { name: "Emerald", color: "#2ecc71" },
      { name: "PeterRiver", color: "#3498db" },
      { name: "Amethyst", color: "#9b59b6" },
      { name: "WetAsphalt", color: "#34495e" },
      { name: "GreenSea", color: "#16a085" },
      { name: "Nephritis", color: "#27ae60" },
      { name: "BelizeHole", color: "#2980b9" },
      { name: "Wisteria", color: "#8e44ad" },
      { name: "MidnightBlue", color: "#2c3e50" },
      { name: "SunFlower", color: "#f1c40f" },
      { name: "Carrot", color: "#e67e22" },
      { name: "Alizarin", color: "#e74c3c" },
      { name: "Clouds", color: "#ecf0f1" },
      { name: "Concrete", color: "#95a5a6" },
      { name: "Orange", color: "#f39c12" },
      { name: "Pumpkin", color: "#d35400" },
      { name: "Pomegranate", color: "#c0392b" },
      { name: "Silver", color: "#bdc3c7" },
      { name: "Asbestos", color: "#7f8c8d" },
    ],
  },
  {
    paletteName: "Flat UI Colors Dutch",
    id: "flat-ui-colors-dutch",
    emoji: "🇳🇱",
    colors: [
      { name: "Sunflower", color: "#FFC312" },
      { name: "Energos", color: "#C4E538" },
      { name: "BlueMartina", color: "#12CBC4" },
      { name: "LavenderRose", color: "#FDA7DF" },
      { name: "BaraRose", color: "#ED4C67" },
      { name: "RadiantYellow", color: "#F79F1F" },
      { name: "AndroidGreen", color: "#A3CB38" },
      { name: "MediterraneanSea", color: "#1289A7" },
      { name: "LavenderTea", color: "#D980FA" },
      { name: "VerryBerry", color: "#B53471" },
      { name: "PuffinsBill", color: "#EE5A24" },
      { name: "PixelatedGrass", color: "#009432" },
      { name: "MerchantMarineBlue", color: "#0652DD" },
      { name: "ForgottenPurple", color: "#9980FA" },
      { name: "HollyHock", color: "#833471" },
      { name: "RedPigment", color: "#EA2027" },
      { name: "TurkishAqua", color: "#006266" },
      { name: "20000LeaguesUnderTheSea", color: "#1B1464" },
      { name: "CircumorbitalRing", color: "#5758BB" },
      { name: "MagentaPurple", color: "#6F1E51" },
    ],
  },
  {
    paletteName: "Flat UI Colors American",
    id: "flat-ui-colors-american",
    emoji: "🇺🇸",
    colors: [
      { name: "LightGreenishBlue", color: "#55efc4" },
      { name: "FadedPoster", color: "#81ecec" },
      { name: "GreenDarnerTail", color: "#74b9ff" },
      { name: "ShyMoment", color: "#a29bfe" },
      { name: "CityLights", color: "#dfe6e9" },
      { name: "MintLeaf", color: "#00b894" },
      { name: "RobinsEggBlue", color: "#00cec9" },
      { name: "ElectronBlue", color: "#0984e3" },
      { name: "ExodusFruit", color: "#6c5ce7" },
      { name: "SoothingBreeze", color: "#b2bec3" },
      { name: "SourLemon", color: "#ffeaa7" },
      { name: "FirstDate", color: "#fab1a0" },
      { name: "PinkGlamour", color: "#ff7675" },
      { name: "Pico8Pink", color: "#fd79a8" },
      { name: "AmericanRiver", color: "#636e72" },
      { name: "BrightYarrow", color: "#fdcb6e" },
      { name: "OrangeVille", color: "#e17055" },
      { name: "Chi-Gong", color: "#d63031" },
      { name: "PrunusAvium", color: "#e84393" },
      { name: "DraculaOrchid", color: "#2d3436" },
    ],
  },
  {
    paletteName: "Flat UI Colors Aussie",
    id: "flat-ui-colors-aussie",
    emoji: "🇦🇺",
    colors: [
      { name: "Beekeeper", color: "#f6e58d" },
      { name: "SpicedNectarine", color: "#ffbe76" },
      { name: "PinkGlamour", color: "#ff7979" },
      { name: "JuneBud", color: "#badc58" },
      { name: "CoastalBreeze", color: "#dff9fb" },
      { name: "Turbo", color: "#f9ca24" },
      { name: "QuinceJelly", color: "#f0932b" },
      { name: "CarminePink", color: "#eb4d4b" },
      { name: "PureApple", color: "#6ab04c" },
      { name: "HintOfIcePack", color: "#c7ecee" },
      { name: "MiddleBlue", color: "#7ed6df" },
      { name: "Heliotrope", color: "#e056fd" },
      { name: "ExodusFruit", color: "#686de0" },
      { name: "DeepKoamaru", color: "#30336b" },
      { name: "SoaringEagle", color: "#95afc0" },
      { name: "GreenlandGreen", color: "#22a6b3" },
      { name: "SteelPink", color: "#be2edd" },
      { name: "Blurple", color: "#4834d4" },
      { name: "DeepCove", color: "#130f40" },
      { name: "WizardGrey", color: "#535c68" },
    ],
  },
  {
    paletteName: "Flat UI Colors British",
    id: "flat-ui-colors-british",
    emoji: "🇬🇧",
    colors: [
      { name: "ProtossPylon", color: "#00a8ff" },
      { name: "Periwinkle", color: "#9c88ff" },
      { name: "Rise", color: "#fbc531" },
      { name: "DownloadProgress", color: "#4cd137" },
      { name: "Seabrook", color: "#487eb0" },
      { name: "VanaDylBlue", color: "#0097e6" },
      { name: "MattPurple", color: "#8c7ae6" },
      { name: "NanohanachaGold", color: "#e1b12c" },
      { name: "SkirretGreen", color: "#44bd32" },
      { name: "Naval", color: "#40739e" },
      { name: "NasturcianFlower", color: "#e84118" },
      { name: "LynxWhite", color: "#f5f6fa" },
      { name: "BlueberrySoda", color: "#7f8fa6" },
      { name: "MazarineBlue", color: "#273c75" },
      { name: "BlueNights", color: "#353b48" },
      { name: "HarleyOrange", color: "#c23616" },
      { name: "HintOfPensive", color: "#dcdde1" },
      { name: "ChainGangGrey", color: "#718093" },
      { name: "PicoVoid", color: "#192a56" },
      { name: "ElectroMagnetic", color: "#2f3640" },
    ],
  },
  {
    paletteName: "Flat UI Colors Spanish",
    id: "flat-ui-colors-spanish",
    emoji: "🇪🇸",
    colors: [
      { name: "JacksonsPurple", color: "#40407a" },
      { name: "C64Purple", color: "#706fd3" },
      { name: "SwanWhite", color: "#f7f1e3" },
      { name: "SummerSky", color: "#34ace0" },
      { name: "CelestialGreen", color: "#33d9b2" },
      { name: "LuckyPoint", color: "#2c2c54" },
      { name: "Liberty", color: "#474787" },
      { name: "HotStone", color: "#aaa69d" },
      { name: "DevilBlue", color: "#227093" },
      { name: "PalmSpringsSplash", color: "#218c74" },
      { name: "FlourescentRed", color: "#ff5252" },
      { name: "SyntheticPumpkin", color: "#ff793f" },
      { name: "CrocodileTooth", color: "#d1ccc0" },
      { name: "MandarinSorbet", color: "#ffb142" },
      { name: "SpicedButterNut", color: "#ffda79" },
      { name: "EyeOfNewt", color: "#b33939" },
      { name: "ChileanFire", color: "#cd6133" },
      { name: "GreyPorcelain", color: "#84817a" },
      { name: "AlamedaOchre", color: "#cc8e35" },
      { name: "Desert", color: "#ccae62" },
    ],
  },
  {
    paletteName: "Flat UI Colors Indian",
    id: "flat-ui-colors-indian",
    emoji: "🇮🇳",
    colors: [
      { name: "OrchidOrange", color: "#FEA47F" },
      { name: "SpiroDiscoBall", color: "#25CCF7" },
      { name: "HoneyGlow", color: "#EAB543" },
      { name: "SweetGarden", color: "#55E6C1" },
      { name: "FallingStar", color: "#CAD3C8" },
      { name: "RichGardenia", color: "#F97F51" },
      { name: "ClearChill", color: "#1B9CFC" },
      { name: "WhitePepper", color: "#F8EFBA" },
      { name: "Keppel", color: "#58B19F" },
      { name: "ShipsOfficer", color: "#2C3A47" },
      { name: "FieryFuchsia", color: "#B33771" },
      { name: "BlueBell", color: "#3B3B98" },
      { name: "GeorgiaPeach", color: "#FD7272" },
      { name: "OasisStream", color: "#9AECDB" },
      { name: "BrightUbe", color: "#D6A2E8" },
      { name: "MagentaPurple", color: "#6D214F" },
      { name: "EndingNavyBlue", color: "#182C61" },
      { name: "SasquatchSocks", color: "#FC427B" },
      { name: "PineGlade", color: "#BDC581" },
      { name: "HighlighterLavender", color: "#82589F" },
    ],
  },
  {
    paletteName: "Flat UI Colors French",
    id: "flat-ui-colors-french",
    emoji: "🇫🇷",
    colors: [
      { name: "FlatFlesh", color: "#fad390" },
      { name: "MelonMelody", color: "#f8c291" },
      { name: "Livid", color: "#6a89cc" },
      { name: "Spray", color: "#82ccdd" },
      { name: "ParadiseGreen", color: "#b8e994" },
      { name: "SquashBlossom", color: "#f6b93b" },
      { name: "MandarinRed", color: "#e55039" },
      { name: "AzraqBlue", color: "#4a69bd" },
      { name: "Dupain", color: "#60a3bc" },
      { name: "AuroraGreen", color: "#78e08f" },
      { name: "IcelandPoppy", color: "#fa983a" },
      { name: "TomatoRed", color: "#eb2f06" },
      { name: "YueGuangBlue", color: "#1e3799" },
      { name: "GoodSamaritan", color: "#3c6382" },
      { name: "Waterfall", color: "#38ada9" },
      { name: "CarrotOrange", color: "#e58e26" },
      { name: "JalapenoRed", color: "#b71540" },
      { name: "DarkSapphire", color: "#0c2461" },
      { name: "ForestBlues", color: "#0a3d62" },
      { name: "ReefEncounter", color: "#079992" },
    ],
  },
  {
    paletteName: "Ocean Breeze",
    id: "ocean-breeze",
    emoji: "🌊",
    colors: [
      { name: "Ocean Blue", color: "#0077be" },
      { name: "Sandy Shore", color: "#eedcb3" },
      { name: "Sunset Pink", color: "#ff6b6b" },
      { name: "Seagull Grey", color: "#d2d4d8" },
      { name: "Aqua Splash", color: "#38a3a5" },
      { name: "Turquoise Sea", color: "#0a9396" },
      { name: "Sailor's Delight", color: "#ff5e5b" },
      { name: "Coral Reef", color: "#fc5185" },
      { name: "Beach Dune", color: "#f5c92d" },
      { name: "Coconut Cream", color: "#c7ecee" },
      { name: "Tropical Teal", color: "#079992" },
      { name: "Starfish Orange", color: "#ff793f" },
      { name: "Driftwood Brown", color: "#786fa6" },
      { name: "Seafoam Green", color: "#80ffdb" },
      { name: "Seashell White", color: "#f3f9d2" },
      { name: "Skyline Blue", color: "#56cfe1" },
      { name: "Sandcastle Beige", color: "#efe9e7" },
      { name: "Misty Morning", color: "#b7b7a4" },
    ],
  },
  {
    paletteName: "Forest Retreat",
    id: "forest-retreat",
    emoji: "🌲",
    colors: [
      { name: "Moss Green", color: "#6e8b75" },
      { name: "Sunlit Meadow", color: "#b5e3b9" },
      { name: "Leafy Canopy", color: "#679436" },
      { name: "Woodland Brown", color: "#5d4037" },
      { name: "Misty Pine", color: "#95a19f" },
      { name: "Fern Green", color: "#4b6e61" },
      { name: "Amber Autumn", color: "#d2aa5c" },
      { name: "Pinecone Brown", color: "#473335" },
      { name: "Forest Fog", color: "#bcc0c2" },
      { name: "Maple Leaf Red", color: "#b80c09" },
      { name: "Golden Oak", color: "#c6893f" },
      { name: "River Rock Grey", color: "#727272" },
      { name: "Whispering Wind", color: "#e3e3e3" },
      { name: "Wildflower Violet", color: "#8675a9" },
      { name: "Evergreen Grove", color: "#00441b" },
      { name: "Twilight Blue", color: "#29434e" },
      { name: "Morning Mist", color: "#a3a3a3" },
      { name: "Rustling Leaves", color: "#d2b58e" },
    ],
  },
  {
    "paletteName": "Sun-Kissed Island",
    "id": "sun-kissed-island",
    "emoji": "☀️",
    "colors": [
      { "name": "Mango", "color": "#ffc048" },
      { "name": "Pineapple", "color": "#f2e88c" },
      { "name": "Papaya", "color": "#ff9933" },
      { "name": "Hibiscus Red", "color": "#e53935" },
      { "name": "Emerald Green", "color": "#2ecc71" },
      { "name": "Rainforest", "color": "#00a878" },
      { "name": "Coconut Milk", "color": "#f8f9f1" },
      { "name": "Sandy Beach", "color": "#e2cfce" },
      { "name": "Turquoise", "color": "#4ca3d9" },
      { "name": "Ocean Depths", "color": "#003087" },
      { "name": "Coral Pink", "color": "#f5828e" },
      { "name": "Sunset Glow", "color": "#ff7f50" },
      { "name": "Driftwood Grey", "color": "#9b9aa3" },
      { "name": "Starry Night", "color": "#34495e" },
      { "name": "Volcanic Rock", "color": "#434a54" },
      { "name": "Sea Glass Teal", "color": "#2aa198" },
      { "name": "Plumeria White", "color": "#f1f5f0" },
    ]
  },
  {
    "paletteName": "Desert Bloom",
    "id": "desert-bloom",
    "emoji": "️",
    "colors": [
      { "name": "Terracotta", "color": "#e0444e" },
      { "name": "Sandstone", "color": "#f9f2e7" },
      { "name": "Clay Brick", "color": "#c62828" },
      { "name": "Sage Green", "color": "#a5b3c6" },
      { "name": "Dusty Rose", "color": "#f4c2c2" },
      { "name": "Desert Sky", "color": "#70a1ff" },
      { "name": "Prickly Pear", "color": "#4d964c" },
      { "name": "Sun-bleached Bone", "color": "#faf0e6" },
      { "name": "Canyon Red", "color": "#ad0000" },
      { "name": "Golden Hour", "color": "#f5b651" },
      { "name": "Lavender", "color": "#d6d8e0" },
      { "name": "Midnight", "color": "#000000" },
      { "name": "Ocotillo Yellow", "color": "#ffc107" },
      { "name": "Creosote Bush", "color": "#29372a" },
      { "name": "Turquoise", "color": "#43cea2" },
      { "name": "Cactus Flower Pink", "color": "#f08080" },
      { "name": "Mesquite Brown", "color": "#78654b" },
    ]
  },
  {
    paletteName: "Pastel Dream",
    id: "pastel-dream",
    emoji: "🌈",
    colors: [
      { name: "Lavender", color: "#d7aefb" },
      { name: "Baby Blue", color: "#aed9e0" },
      { name: "Peach", color: "#fcb9b2" },
      { name: "Mint", color: "#b7efcd" },
      { name: "Buttercup", color: "#fee089" },
      { name: "Rose Quartz", color: "#f7cac9" },
      { name: "Periwinkle", color: "#c9def1" },
      { name: "Cotton Candy", color: "#f8bbd0" },
      { name: "Pale Lemon", color: "#fffdd0" },
      { name: "Sky Blue", color: "#a0d2db" },
      { name: "Apricot", color: "#f9a875" },
      { name: "Seafoam", color: "#88d8b0" },
      { name: "Coral", color: "#f7786b" },
      { name: "Lilac", color: "#b2abe0" },
      { name: "Turquoise", color: "#7bc4c4" },
      { name: "Cream", color: "#fff1cf" },
      { name: "Mauve", color: "#ebc7d4" },
      { name: "Pearl", color: "#f0efeb" },
    ],
  },
  {
    paletteName: "Vintage Vibes",
    id: "vintage-vibes",
    emoji: "📻",
    colors: [
      { name: "Antique Gold", color: "#b28e5e" },
      { name: "Dusty Rose", color: "#b36a71" },
      { name: "Faded Mint", color: "#c3e2be" },
      { name: "Retro Blue", color: "#7697a0" },
      { name: "Old Lace", color: "#f2e2ce" },
      { name: "Worn Denim", color: "#5a6e7f" },
      { name: "Weathered Brick", color: "#a62a5e" },
      { name: "Aged Ivory", color: "#f9e6cf" },
      { name: "Rusty Orange", color: "#d97b56" },
      { name: "Faded Teal", color: "#9fb7b9" },
      { name: "Vintage Violet", color: "#887bb4" },
      { name: "Distressed Green", color: "#a4b787" },
      { name: "Retro Pink", color: "#ffabb9" },
      { name: "Ancient Bronze", color: "#6e5346" },
      { name: "Timeworn Turquoise", color: "#6b8f96" },
      { name: "Yellowed Paper", color: "#f8f3e1" },
      { name: "Retro Red", color: "#aa445f" },
      { name: "Faded Sepia", color: "#a89f93" },
    ],
  },
  {
    paletteName: "Neon Lights",
    id: "neon-lights",
    emoji: "💡",
    colors: [
      { name: "Electric Pink", color: "#ff66ff" },
      { name: "Laser Lime", color: "#bfff00" },
      { name: "Glowing Green", color: "#33ff33" },
      { name: "Vivid Violet", color: "#8a2be2" },
      { name: "Radiant Red", color: "#ff0033" },
      { name: "Fluorescent Fuchsia", color: "#ff00ff" },
      { name: "Bright Blue", color: "#3366ff" },
      { name: "Luminous Lemon", color: "#ffff33" },
      { name: "Shocking Orange", color: "#ff9933" },
      { name: "Neon Aqua", color: "#00ffff" },
      { name: "Hot Pink", color: "#ff69b4" },
      { name: "Electric Lime", color: "#ccff00" },
      { name: "Glowstick Green", color: "#77ff33" },
      { name: "Atomic Amber", color: "#ffc300" },
      { name: "Blazing Blue", color: "#007fff" },
      { name: "Vibrant Violet", color: "#cd00ff" },
      { name: "Day-Glo Green", color: "#39ff14" },
      { name: "Ultra Violet", color: "#5a4fcf" },
    ],
  },
  {
    paletteName: "Candy Crush",
    id: "candy-crush",
    emoji: "🍬",
    colors: [
      { name: "Bubblegum Pink", color: "#ff6b6b" },
      { name: "Lemon Drop", color: "#ffec99" },
      { name: "Spearmint Green", color: "#90ee90" },
      { name: "Tangerine Tang", color: "#ffcc66" },
      { name: "Blue Raspberry", color: "#70a1ff" },
      { name: "Cotton Candy Blue", color: "#a4c7ff" },
      { name: "Sour Apple", color: "#a5d6a7" },
      { name: "Cherry Chew", color: "#ff7f7f" },
      { name: "Grape Gumdrop", color: "#b19cd9" },
      { name: "Pineapple Punch", color: "#ffeb3b" },
      { name: "Licorice Twist", color: "#3d3d3d" },
      { name: "Watermelon Whirl", color: "#ff8282" },
      { name: "Orange Crush", color: "#ff8c42" },
      { name: "Berry Blast", color: "#a52a2a" },
      { name: "Creamy Caramel", color: "#af7ac5" },
      { name: "Strawberry Swirl", color: "#ff4d4d" },
      { name: "Butterscotch Bliss", color: "#ffcc00" },
      { name: "Peppermint Pop", color: "#66cccc" },
    ],
  },
  {
    paletteName: "Google",
    id: "google",
    emoji: "🌐",
    colors: [
      { name: "Google Blue", color: "#4285F4" },
      { name: "Google Red", color: "#DB4437" },
      { name: "Google Yellow", color: "#F4B400" },
      { name: "Google Green", color: "#0F9D58" },
      { name: "Google Black", color: "#000000" },
      { name: "Google Grey", color: "#666666" },
      { name: "Google White", color: "#FFFFFF" },
      { name: "Google Light Grey", color: "#EEEEEE" },
      { name: "Google Dark Grey", color: "#CCCCCC" },
      { name: "Google Light Blue", color: "#AED6F1" },
      { name: "Google Light Red", color: "#FADBD8" },
      { name: "Google Light Yellow", color: "#F9E79F" },
      { name: "Google Light Green", color: "#ABEBC6" },
      { name: "Google Dark Blue", color: "#1F618D" },
      { name: "Google Dark Red", color: "#922B21" },
      { name: "Google Dark Yellow", color: "#B7950B" },
      { name: "Google Dark Green", color: "#186A3B" },
      { name: "Google Pink", color: "#E6B0AA" },
    ],
  },
  {
    paletteName: "Facebook",
    id: "facebook",
    emoji: "📘",
    colors: [
      { name: "Facebook Blue", color: "#4267B2" },
      { name: "Facebook Dark Blue", color: "#0A3259" },
      { name: "Facebook Light Blue", color: "#5B7AA2" },
      { name: "Facebook Grey", color: "#CCCCCC" },
      { name: "Facebook White", color: "#FFFFFF" },
      { name: "Facebook Black", color: "#000000" },
      { name: "Facebook Green", color: "#38A1F3" },
      { name: "Facebook Red", color: "#FF6347" },
      { name: "Facebook Pink", color: "#FFB6C1" },
      { name: "Facebook Purple", color: "#8A2BE2" },
      { name: "Facebook Yellow", color: "#FFD700" },
      { name: "Facebook Orange", color: "#FFA500" },
      { name: "Facebook Brown", color: "#A52A2A" },
      { name: "Facebook Light Green", color: "#00FF00" },
      { name: "Facebook Light Red", color: "#FF6666" },
      { name: "Facebook Light Yellow", color: "#FFFF00" },
      { name: "Facebook Light Orange", color: "#FFA07A" },
      { name: "Facebook Light Purple", color: "#DA70D6" },
    ],
  },
  {
    paletteName: "Apple",
    id: "apple",
    emoji: "🍏",
    colors: [
      { name: "Apple Black", color: "#000000" },
      { name: "Apple Grey", color: "#666666" },
      { name: "Apple Silver", color: "#C0C0C0" },
      { name: "Apple White", color: "#FFFFFF" },
      { name: "Apple Green", color: "#4CAF50" },
      { name: "Apple Red", color: "#FF4136" },
      { name: "Apple Yellow", color: "#FFD700" },
      { name: "Apple Blue", color: "#0074D9" },
      { name: "Apple Orange", color: "#FF851B" },
      { name: "Apple Pink", color: "#FF69B4" },
      { name: "Apple Purple", color: "#B10DC9" },
      { name: "Apple Brown", color: "#8B4513" },
      { name: "Apple Cyan", color: "#7FDBFF" },
      { name: "Apple Indigo", color: "#4B0082" },
      { name: "Apple Teal", color: "#008080" },
      { name: "Apple Lime", color: "#00FF00" },
      { name: "Apple Maroon", color: "#800000" },
      { name: "Apple Navy", color: "#000080" },
    ],
  },  
];
